name = "anastasia-labs/aiken-project"
version = "0.0.1"
compiler = "v1.1.4"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken project that depends on the Plutarch project"

[repository]
user = "anastasia-labs"
project = "aiken-project"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.1.0"
source = "github"

[config]
